### ISSUE TITLE
Requires Using XCode's Deprecated Build System

### ISSUE THREAD

**Issue by colterh** [SuperAwesomeLTD/sa-unity-sdk#18]
The SDK setup [instructions](https://sa-unity-sdk.superawesome.tv/docs/add-sdk) state that all versions of the SDK, including the most recent (8.0.5), require using XCode's deprecated build system.

> SDK version 8.0.5 or older are incompatible with Xcode's New Build System. Please switch the build system from New to Legacy by going to File -> Project Settings and changing the Build System drop down.

Is there an ETA on a new version of the Unity SDK that does not require using deprecated functionality? In our experience, the XCode team removes deprecated functionality very quickly, and new Unity versions typically require keeping XCode fully updated.

Along the same lines, we are hopeful that future versions of the SA SDK won't require manual tweaks in XCode to have functioning builds. These required manual tweaks prevent fully automated builds and the use of Unity's Cloud Builds.

**Comment by dnharjani-sa** [comment]
This is a version of 8.0.5 using the new XCode build system: https://aa-sdk.s3.eu-west-1.amazonaws.com/releases/SuperAwesomeSDK-8.0.5-new-build-system.Unity.full.unitypackage.zip

Future versions of Unity builds will all be on the new build system.
