### ISSUE TITLE
Release 8.0.5 doesn't have a compiled Unity package

### ISSUE THREAD

**Issue by JonathanReid** [SuperAwesomeLTD/sa-unity-sdk#19]
When trying to compile this source manually, I also get errors about a missing android videoplayer repo as well:
https://github.com/SuperAwesomeLTD/sa-mobile-lib-android-videoplayer.git

Can the package be released as per the other releases?

**Comment by gnhn** [comment]
Please try with latest version. Hopefully, it should solve this problem.
