### ISSUE TITLE
Adverts are not shown when using Android OS 5

### ISSUE THREAD

**Issue by JonathanReid** [SuperAwesomeLTD/sa-unity-sdk#21]
Adverts don't appear to be shown to the user when using OS 5. They sometimes will start to be shown, as in the black fullscreen holder appears, but then they are swiftly followed by the "adFailedToShow" event and exited.

**Comment by gunhansancar** [comment]
@JonathanReid do you still need help about this issue? I'll close the issue since too much time passed but feel free to create a new issue if you experience issues.
