### ISSUE TITLE
License concerns

### ISSUE THREAD

**Issue by Wolfos** [SuperAwesomeLTD/sa-unity-sdk#3]
Hi,

I see that this library uses the GPL license. However, this license requires any software that uses it, or parts of it, to be open sourced and also released under a GPL license. Additionally Apple has removed apps from the App Store in the past for using GPL code.

I doubt this is intentional, so maybe you can switch to a more permissive license such as Apache or MIT.

**Comment by devgabrielcoman** [comment]
Hey @Wolfos Thanks for spotting that out.
Actually the license should have been **LGPL**, not **GPL**. 

As per https://www.gnu.org/licenses/lgpl-3.0.en.html

it'll allow you to incorporate SuperAwesome SDKs into your app without the caveat that you also have to open source it. The other restrictions of the GPL license will still apply though.

I'll update the license in all repositories.

**Comment by Wolfos** [comment]
Thanks for the quick reply. LGPL will work.
