### ISSUE TITLE
Building in unity cloud

### ISSUE THREAD

**Issue by dominicdev** [SuperAwesomeLTD/sa-unity-sdk#5]
I'm trying to build it in unity cloud but I'm getting an error , my problem was I dont have IOS addition settings cause I'm working in windows 10

649: error: exportArchive: IPA processing failed
650: Error Domain=IDEFoundationErrorDomain Code=1 "IPA processing failed" UserInfo={NSLocalizedDescription=IPA processing failed}
651: Error packaging up the application
652: [!] Error packaging up the application

**Comment by gunhansancar** [comment]
Is this still the case?

**Comment by dominicdev** [comment]
> Is this still the case?

yes right now skip this issue as for now in ios.
