### ISSUE TITLE
Error: 'SuperAwesome.framework' was built for iOS + iOS Simulator.

### ISSUE THREAD

**Issue by LeonardoDemartino** [SuperAwesomeLTD/sa-unity-sdk#9]
Hello! I have just updated our SA SDK (SuperAwesomeSDK-7.2.19.unitypackage) and also updated Xcode to 12.3 and this error shows up when building:
`error: Building for iOS, but the embedded framework 'SuperAwesome.framework' was built for iOS + iOS Simulator. (in target 'Unity-iPhone' from project 'Unity-iPhone')`

A workaround is to set Validate Workspace to Yes on Unity-iPhone build settings in Xcode.

According to Apple "iOS and iOS Simulator code has never been supported in the same binary":
Source: https://developer.apple.com/forums/thread/669411

Please fix this ASAP, thanks a lot!

**Comment by dominicdev** [comment]
same.. where using SA for our Kids app then test in unity cloud build and using windows PC.. without Xcode.. it there any we can do without addition setup for ios?

**Comment by colterh** [comment]
As far as we know, the only way to get functional iOS builds is to follow the "Additional steps for iOS Builds" on the [SDK instructions page](https://sa-unity-sdk.superawesome.tv/docs/add-sdk). Requiring manual steps in XCode really makes it cumbersome to create builds, thus making it difficult to keep the SA SDK in our games.

**Comment by dnharjani-sa** [comment]
Fixed in newer versions of the SDK.
